name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Bootstrap
        run: bash bootstrap.sh
      - name: Install dependencies
        run: npm ci
      - name: Build libs
        run: npm run build-lib
