name: Publish Package to npm
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish under'
        required: false
        default: 'latest'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: bash bootstrap.sh
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build-lib:production
      - name: Publish to npm
        run: npm publish --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create and push git tag
        run: |
          version=$(node -p "require('./package.json').version")
          git tag -a "v$version" -m "Version $version"
          git push origin "v$version"
