name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish under'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: bash bootstrap.sh
      - run: npm ci
      - run: npm run build-lib:production
      - run: npm publish --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
