name: Publish Package to npm
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish under'
        required: false
        default: 'latest'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - name: Check if version exists on npm
        id: check-version
        run: |
          version=$(node -p "require('./package.json').version")
          name=$(node -p "require('./package.json').name")
          if npm view ${name}@${version} > /dev/null 2>&1; then
            echo "Version ${version} already exists on npm."
            exit 1
          fi
      - run: bash bootstrap.sh
      - name: Install dependencies
        run: npm ci
      - name: Build dependencies
        run: npm run build-lib:production
      - name: Publish to npm
        run: npm publish --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create and push git tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"
          version=$(node -p "require('./package.json').version")
          git tag -a "v$version" -m "Version $version"
          git push origin "v$version"
